# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dc8bc6b2a27a79c0512c596d927989a48f83daac38b622daaa564db6a8d03f313cd82cd53bcc1bcda6497c65492db9fb4b3d812e8c4b6848ae43901535ceeae

test:
  secret_key_base: c1ad640833ff4eddfe6ec6f5c3efdf64990ab6e63cb744e6c02e0b6420dc8a1f86f258835185c071ec008dfa0c60be2b462e27afbd5ff28c2eb883d2cf0d6dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
# I don't always follow rules.  Especially when security is not an issue.
# But YOU should follow rules, especially when security IS an issue.
production:
  secret_key_base: 2dc8bc6b2a27a79c0512c596d927989a48f83daac38b622daaa564db6a8d03f313cd82cd53bcc1bcda6497c65492db9fb4b3d812e8c4b6848ae43901535ceeae
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
